// LINT: LEGACY_NAMES

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: tensorflow/compiler/xla/stream_executor/dnn.proto

package stream_executor

import (
	stream_executor "github.com/google/tsl/tsl/go/stream_executor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Symbols defined in public import of tensorflow/tsl/protobuf/dnn.proto.

type DataType = stream_executor.DataType

const DataType_kFloat = stream_executor.DataType_kFloat
const DataType_kDouble = stream_executor.DataType_kDouble
const DataType_kHalf = stream_executor.DataType_kHalf
const DataType_kInt8 = stream_executor.DataType_kInt8
const DataType_kInt32 = stream_executor.DataType_kInt32
const DataType_kComplexFloat = stream_executor.DataType_kComplexFloat
const DataType_kComplexDouble = stream_executor.DataType_kComplexDouble
const DataType_kBF16 = stream_executor.DataType_kBF16
const DataType_kF8E5M2 = stream_executor.DataType_kF8E5M2
const DataType_kF8E4M3FN = stream_executor.DataType_kF8E4M3FN

var DataType_name = stream_executor.DataType_name
var DataType_value = stream_executor.DataType_value

type DataLayout = stream_executor.DataLayout

const DataLayout_kYXDepthBatch = stream_executor.DataLayout_kYXDepthBatch
const DataLayout_kYXBatchDepth = stream_executor.DataLayout_kYXBatchDepth
const DataLayout_kBatchYXDepth = stream_executor.DataLayout_kBatchYXDepth
const DataLayout_kBatchDepthYX = stream_executor.DataLayout_kBatchDepthYX
const DataLayout_kBatchDepthYX4 = stream_executor.DataLayout_kBatchDepthYX4
const DataLayout_kBatchDepthYX32 = stream_executor.DataLayout_kBatchDepthYX32

var DataLayout_name = stream_executor.DataLayout_name
var DataLayout_value = stream_executor.DataLayout_value

type FilterLayout = stream_executor.FilterLayout

const FilterLayout_kOutputInputYX = stream_executor.FilterLayout_kOutputInputYX
const FilterLayout_kOutputYXInput = stream_executor.FilterLayout_kOutputYXInput
const FilterLayout_kOutputInputYX4 = stream_executor.FilterLayout_kOutputInputYX4
const FilterLayout_kOutputInputYX32 = stream_executor.FilterLayout_kOutputInputYX32
const FilterLayout_kInputYXOutput = stream_executor.FilterLayout_kInputYXOutput
const FilterLayout_kYXInputOutput = stream_executor.FilterLayout_kYXInputOutput

var FilterLayout_name = stream_executor.FilterLayout_name
var FilterLayout_value = stream_executor.FilterLayout_value

type ActivationMode = stream_executor.ActivationMode

const ActivationMode_kNone = stream_executor.ActivationMode_kNone
const ActivationMode_kSigmoid = stream_executor.ActivationMode_kSigmoid
const ActivationMode_kRelu = stream_executor.ActivationMode_kRelu
const ActivationMode_kRelu6 = stream_executor.ActivationMode_kRelu6
const ActivationMode_kReluX = stream_executor.ActivationMode_kReluX
const ActivationMode_kTanh = stream_executor.ActivationMode_kTanh
const ActivationMode_kBandPass = stream_executor.ActivationMode_kBandPass
const ActivationMode_kElu = stream_executor.ActivationMode_kElu
const ActivationMode_kLeakyRelu = stream_executor.ActivationMode_kLeakyRelu
const ActivationMode_kGeluExact = stream_executor.ActivationMode_kGeluExact

var ActivationMode_name = stream_executor.ActivationMode_name
var ActivationMode_value = stream_executor.ActivationMode_value

type ConvolutionMode = stream_executor.ConvolutionMode

const ConvolutionMode_CROSS_CORRELATION = stream_executor.ConvolutionMode_CROSS_CORRELATION
const ConvolutionMode_CONVOLUTION = stream_executor.ConvolutionMode_CONVOLUTION

var ConvolutionMode_name = stream_executor.ConvolutionMode_name
var ConvolutionMode_value = stream_executor.ConvolutionMode_value

type ConvolutionKind = stream_executor.ConvolutionKind

const ConvolutionKind_INVALID = stream_executor.ConvolutionKind_INVALID
const ConvolutionKind_FORWARD = stream_executor.ConvolutionKind_FORWARD
const ConvolutionKind_BACKWARD_FILTER = stream_executor.ConvolutionKind_BACKWARD_FILTER
const ConvolutionKind_BACKWARD_DATA = stream_executor.ConvolutionKind_BACKWARD_DATA
const ConvolutionKind_FORWARD_BIAS_ACTIVATION = stream_executor.ConvolutionKind_FORWARD_BIAS_ACTIVATION

var ConvolutionKind_name = stream_executor.ConvolutionKind_name
var ConvolutionKind_value = stream_executor.ConvolutionKind_value

type AlgorithmProto_MathType = stream_executor.AlgorithmProto_MathType

const AlgorithmProto_DEFAULT_MATH = stream_executor.AlgorithmProto_DEFAULT_MATH
const AlgorithmProto_TENSOR_OP_MATH = stream_executor.AlgorithmProto_TENSOR_OP_MATH

var AlgorithmProto_MathType_name = stream_executor.AlgorithmProto_MathType_name
var AlgorithmProto_MathType_value = stream_executor.AlgorithmProto_MathType_value

type TensorDescriptorProto = stream_executor.TensorDescriptorProto
type TensorDescriptorProto_DataLayout = stream_executor.TensorDescriptorProto_DataLayout
type TensorDescriptorProto_FilterLayout = stream_executor.TensorDescriptorProto_FilterLayout
type AlgorithmProto = stream_executor.AlgorithmProto
type AlgorithmConfigProto = stream_executor.AlgorithmConfigProto
type AlgorithmConfigProto_Algorithm = stream_executor.AlgorithmConfigProto_Algorithm
type AlgorithmConfigProto_AlgorithmNoScratch = stream_executor.AlgorithmConfigProto_AlgorithmNoScratch
type AlgorithmConfigProto_ScratchSize = stream_executor.AlgorithmConfigProto_ScratchSize
type ConvolutionDescriptorProto = stream_executor.ConvolutionDescriptorProto

var File_tensorflow_compiler_xla_stream_executor_dnn_proto protoreflect.FileDescriptor

var file_tensorflow_compiler_xla_stream_executor_dnn_proto_rawDesc = []byte{
	0x0a, 0x31, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x6d,
	0x70, 0x69, 0x6c, 0x65, 0x72, 0x2f, 0x78, 0x6c, 0x61, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x5f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x2f, 0x64, 0x6e, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x19, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x65, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x6f, 0x72, 0x2e, 0x64, 0x6e, 0x6e, 0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x1a, 0x21,
	0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x74, 0x73, 0x6c, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x6e, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x74, 0x65, 0x6e, 0x73, 0x6f,
	0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77,
	0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x6f, 0x72, 0x50, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_tensorflow_compiler_xla_stream_executor_dnn_proto_goTypes = []interface{}{}
var file_tensorflow_compiler_xla_stream_executor_dnn_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tensorflow_compiler_xla_stream_executor_dnn_proto_init() }
func file_tensorflow_compiler_xla_stream_executor_dnn_proto_init() {
	if File_tensorflow_compiler_xla_stream_executor_dnn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tensorflow_compiler_xla_stream_executor_dnn_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tensorflow_compiler_xla_stream_executor_dnn_proto_goTypes,
		DependencyIndexes: file_tensorflow_compiler_xla_stream_executor_dnn_proto_depIdxs,
	}.Build()
	File_tensorflow_compiler_xla_stream_executor_dnn_proto = out.File
	file_tensorflow_compiler_xla_stream_executor_dnn_proto_rawDesc = nil
	file_tensorflow_compiler_xla_stream_executor_dnn_proto_goTypes = nil
	file_tensorflow_compiler_xla_stream_executor_dnn_proto_depIdxs = nil
}
